docs: replace deprecated npx option
typicode/husky pull request #1070
Opened 2021-10-30 10:54 UTC by sibiraj-s

> The --no-install option is deprecated, and will be converted to --no

https://docs.npmjs.com/cli/v7/commands/npx#compatibility-with-older-npx-versions.

2021-12-29 12:47 UTC, sibiraj-s commented
Still valid.

2021-12-31 07:48 UTC, devinrhode2 commented
Is --no-install removed or just deprecated?

2021-12-31 07:55 UTC, sibiraj-s commented
Its deprecated. See here for more details https://docs.npmjs.com/cli/v8/commands/npx#compatibility-with-older-npx-versions

2021-12-31 18:19 UTC, devinrhode2 commented
Maybe it would be better to keep using --no-install for greater compatibility?

2022-01-04 15:42 UTC, sibiraj-s commented
It's been over a year since it got deprecated from v7, now we have v8. Majority of projects appears to be using npm7. IMO, we should move forward.

2022-02-17 07:53 UTC, typicode commented
Tricky one, though I do agree.

Node 12 and 14 are still maintained and use npm 6 (so there are still people using them). Let's merge this PR in April when Node 12 is out of life.

2022-02-17 10:42 UTC, sibiraj-s commented
> Tricky one, though I do agree.
> 
> Node 12 and 14 are still maintained and use npm 6 (so there are still people using them). Let's merge this PR in April when Node 12 is out of life.

Agreed 👍

2022-04-25 23:55 UTC, devinrhode2 commented
> Node 12 and 14 are still maintained and use npm 6 (so there are still people using them). Let's merge this PR in April when Node 12 is out of life.

Hey! April has come! `stale` `bot` has served it's true purpose. :)

2022-04-26 00:06 UTC, devinrhode2 reviewed
LGTM :) 👍

2022-04-26 03:47 UTC, sibiraj-s commented
Not seeing an option to reopen the PR.

2022-04-27 20:49 UTC, typicode requested changes

2022-04-27 20:49 UTC, typicode commented on docs/README.md
> +npx husky add .husky/commit-msg 'npx --no commitlint -- --edit "$1"'
```suggestion
npx husky add .husky/commit-msg 'npx --no commitlint --edit "$1"'
```
It seems unnecessary with npx
https://docs.npmjs.com/cli/v8/commands/npx#examples

2022-04-27 20:49 UTC, typicode commented on docs/README.md
> +npx --no commitlint -- --edit $1
```suggestion
npx --no commitlint --edit $1
```

2022-04-28 06:48 UTC, typicode approved these changes

2022-04-28 06:48 UTC, merged