Changed default hook script to avoid fail on Windows installations
typicode/husky pull request #1402
Opened 2024-03-06 11:03 UTC by Jxlle

Recently in Husky v9, an issue came up on Windows installations using Husky (in my case, wsl on Windows), where the default script used by the hooks failed because the path variable had a slash in the other direction (`\`). This commit changes this base script to the following:

```
#!/usr/bin/env sh
PATH=${0%/*}
. "${PATH%\\*}/h"
```

This should work with both types of path separators.

_**Note**: Paths that contain both slashes might still have problems as the above script can delete two slashes instead of one (if they are different). To avoid this, an if statement can be added but I'm not sure if this is required due to not knowing how common this situation is._

2024-04-09 12:29 UTC, SoyDiego commented
> Recently in Husky v9, an issue came up on Windows installations using Husky (in my case, wsl on Windows), where the default script used by the hooks fails on some Git GUI's (in my case it was GitKraken using a Windows installed Git executable) because the path variable used in the script has a slash in the other direction (`\`). This commit changes this base script to the following:
> 
> ```
> #!/usr/bin/env sh
> SUB=${0%/*}
> . "${SUB%\\*}/h"
> ```
> 
> instead of:
> 
> ```
> #!/usr/bin/env sh
> . "${0%/*}/h"
> ```
> 
> This should work with both types of path separators.
> 
> **For me, this change in script fixed all my issues but I'm not sure why this problem is even occurring. I saw that some of the hooks (such as pre-commit) DO use a slash in the other direction (`/`) within GitKraken. Using the hooks via the Git cli on my Windows machine does NOT give problems for the original script.**
> 
> _**Note**: Paths that contain both slashes might still have problems as the above script can delete two slashes instead of one (if they are different). To avoid this, an if statement can be added but I'm not sure if this is required due to not knowing how common this situation is._

Hi, I was watching your PR and I don't know if I have the same problem.
My project is like the documentation:

![image](https://github.com/typicode/husky/assets/19764334/db3435b5-88bd-49d4-b717-38b98a6affc7)

- I installed `husky`
- I did `npx husky init`
- Last command, edited my `package.json` and I replaced the line `prepare` for `"prepare": "cd .. && husky 'My Project/.husky'"`

When I do this, only is creating a file `pre-commit` but I cannot see the folder `_`

![image](https://github.com/typicode/husky/assets/19764334/c0a58d38-87dc-4117-9bc7-cf40d53a8ad6)


I'm doing manually `npm run prepare` and now I can see the folder `_`

![image](https://github.com/typicode/husky/assets/19764334/2fd850c0-437d-4795-9a66-54d165f1322b)

Finally I'm trying to do a commit but always I have the same error:

![image](https://github.com/typicode/husky/assets/19764334/ce6bad8e-73ae-44c8-a098-288f7b5a52cd)


What I'm doing wrong. I'm trying in Linux, Mac and Windows and always I have the same problem or sometimes I'm receiving the message `.git not found`.

Any help? @Jxlle @typicode 

Thanks!

2024-06-05 11:29 UTC, ccerrillo requested changes
Hi @Jxlle, thanks for this!

I think a better aproach is to replace
`"\${0%/*}/h"`
 with
 `"\$(dirname "\$0")/h"`
 
Can you change this?

@typicode What do you think about this? Can it be merged with this change?

2024-06-06 11:30 UTC, Jxlle commented
> I think a better aproach is to replace `"\${0%/*}/h"` with `"\$(dirname "\$0")/h"`
> 
> Can you change this?

Hi @ccerrillo, do you mean like this?:

`#!/usr/bin/env sh\nSUB=\$(dirname "\$0")\n. "\${SUB%\\\\*}/h"`

which is

```
#!/usr/bin/env sh
SUB=$(dirname "$0")
. "${SUB%\\*}/h"
```

2024-06-07 13:01 UTC, ccerrillo commented
Hi @Jxlle,

No, with dirname there is no need to apply the regex to replace last part. just replace 
`"\${0%/*}/h"`
with
`"\$(dirname "\$0")/h"`

So the result is:

```
#!/usr/bin/env sh
. "\$(dirname "\$0")/h"
```

2024-06-12 11:41 UTC, ccerrillo commented
Hi @Jxlle I have found a way to completely solve the issue. The problem arises because GitKraken calls the script with the Windows path format, so using cygpath when available fixes it, along with using dirname in Husky hooks.
This is the pull request #1458 
@typicode can you look at it?

2024-06-12 12:30 UTC, Jxlle commented
> Hi @Jxlle I have found a way to completely solve the issue. The problem arises because GitKraken calls the script with the Windows path format, so using cygpath when available fixes it, along with using dirname in Husky hooks. This is the pull request #1458 @typicode can you look at it?

Looks great! Guess I'll close this PR as soon as @typicode has taken a look at yours

2024-07-25 15:42 UTC, closed without merging